/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/5R6k3PY0bMY
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { ResponsiveBar } from "@nivo/bar"
import { CardContent, Card, CardTitle, CardDescription, CardHeader } from "@/components/ui/card"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

export function uicomponent() {
  return (
    (<div className="flex min-h-screen w-full flex-col">
      <header
        className="flex items-center h-14 border-b gap-4 px-4 md:h-16 lg:gap-6 xl:px-6 dark:border-gray-800">
        <Link className="items-center gap-2 font-semibold" href="#">
          Expense Tracker
        </Link>
      </header>
      <div className="flex flex-1 min-h-[calc(100vh_-_theme(spacing.14))] w-full">
        <div
          className="hidden border-r border-gray-200 bg-gray-100/40 md:flex flex-col w-[250px] dark:border-gray-800 dark:bg-gray-800/40">
          <nav
            className="flex-1 overflow-auto grid items-start px-4 text-sm font-medium">
            <Link
              className="flex items-center gap-3 rounded-lg bg-gray-100 px-3 py-2 text-gray-900  transition-all hover:text-gray-900 dark:bg-gray-800 dark:text-gray-50 dark:hover:text-gray-50"
              href="#">
              <HomeIcon className="h-4 w-4" />
              Home
            </Link>
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#">
              <CreditCardIcon className="h-4 w-4" />
              Transactions
            </Link>
            <Link
              className="flex items-center gap-3 rounded-lg px-3 py-2 text-gray-500 transition-all hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#">
              <ListIcon className="h-4 w-4" />
              Categories
            </Link>
          </nav>
        </div>
        <div className="flex-1 flex flex-col gap-4 p-4 md:gap-8 md:p-10">
          <div className="flex items-center gap-4">
            <h1 className="font-semibold text-lg md:text-2xl">Dashboard</h1>
            <Button size="sm">Add transaction</Button>
          </div>
          <Card>
            <CardContent className="flex flex-col gap-4">
              <div className="grid gap-2 md:grid-cols-2">
                <div className="flex flex-col gap-1">
                  <h2 className="font-semibold text-base">Total spent</h2>
                  <h3 className="font-bold text-lg">$1,234.56</h3>
                </div>
                <div className="flex flex-col gap-1">
                  <h2 className="font-semibold text-base">This month</h2>
                  <h3 className="font-bold text-lg">$345.67</h3>
                </div>
              </div>
              <div className="flex items-center gap-4">
                <div className="w-full">
                  <BarChart className="h-[200px] max-w-2xl w-full" />
                </div>
                <div className="grid gap-1">
                  <div className="flex items-center gap-2">
                    <CreditCardIcon className="h-4 w-4" />
                    <div className="font-medium">Shopping</div>
                    <div className="ml-auto">25%</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <PackageIcon className="h-4 w-4" />
                    <div className="font-medium">Food</div>
                    <div className="ml-auto">20%</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <HomeIcon className="h-4 w-4" />
                    <div className="font-medium">Rent</div>
                    <div className="ml-auto">30%</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <UsersIcon className="h-4 w-4" />
                    <div className="font-medium">Utilities</div>
                    <div className="ml-auto">25%</div>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Recent transactions</CardTitle>
              <CardDescription>View your recent transactions</CardDescription>
            </CardHeader>
            <CardContent>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Date</TableHead>
                    <TableHead>Description</TableHead>
                    <TableHead>Category</TableHead>
                    <TableHead className="text-right">Amount</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  <TableRow>
                    <TableCell>2023-06-14</TableCell>
                    <TableCell className="font-medium">Grocery shopping</TableCell>
                    <TableCell>Food</TableCell>
                    <TableCell className="text-right">$50.00</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-06-13</TableCell>
                    <TableCell className="font-medium">Dinner with friends</TableCell>
                    <TableCell>Entertainment</TableCell>
                    <TableCell className="text-right">$80.00</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-06-12</TableCell>
                    <TableCell className="font-medium">Monthly subscription</TableCell>
                    <TableCell>Utilities</TableCell>
                    <TableCell className="text-right">$30.00</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-06-11</TableCell>
                    <TableCell className="font-medium">Coffee at the cafe</TableCell>
                    <TableCell>Coffee</TableCell>
                    <TableCell className="text-right">$10.00</TableCell>
                  </TableRow>
                  <TableRow>
                    <TableCell>2023-06-10</TableCell>
                    <TableCell className="font-medium">Shopping at the mall</TableCell>
                    <TableCell>Shopping</TableCell>
                    <TableCell className="text-right">$100.00</TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </div>
      </div>
    </div>)
  );
}


function HomeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m3 9 9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
      <polyline points="9 22 9 12 15 12 15 22" />
    </svg>)
  );
}


function CreditCardIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="14" x="2" y="5" rx="2" />
      <line x1="2" x2="22" y1="10" y2="10" />
    </svg>)
  );
}


function ListIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="8" x2="21" y1="6" y2="6" />
      <line x1="8" x2="21" y1="12" y2="12" />
      <line x1="8" x2="21" y1="18" y2="18" />
      <line x1="3" x2="3.01" y1="6" y2="6" />
      <line x1="3" x2="3.01" y1="12" y2="12" />
      <line x1="3" x2="3.01" y1="18" y2="18" />
    </svg>)
  );
}


function BarChart(props) {
  return (
    (<div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data" />
    </div>)
  );
}


function PackageIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m7.5 4.27 9 5.15" />
      <path
        d="M21 8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16Z" />
      <path d="m3.3 7 8.7 5 8.7-5" />
      <path d="M12 22V12" />
    </svg>)
  );
}


function UsersIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2" />
      <circle cx="9" cy="7" r="4" />
      <path d="M22 21v-2a4 4 0 0 0-3-3.87" />
      <path d="M16 3.13a4 4 0 0 1 0 7.75" />
    </svg>)
  );
}
